#!/usr/bin/env bash
# notices.sh — regenerate THIRD-PARTY.md from the dependency graph.
#
# History
#   2026-08-09  A. Sigdel  Created.
#
# Usage
#   scripts/notices.sh            # rewrite THIRD-PARTY.md
#   scripts/notices.sh --check    # fail if it is out of date
#
# Generated rather than written. A hand-maintained list of 287 packages is a
# second copy of Cargo.lock that goes stale on the first `cargo update`, which
# is the failure this repository legislates against everywhere else.
#
# Not `cargo about`, which would be a toolchain dependency installed to check a
# file nobody reads between releases. `cargo metadata` and `jq` are both already
# required, and the thing that actually needs a person is the preamble below.
#
# --all-features on purpose: git, memory and android are off by default, and
# they are exactly the features a phone build turns on. Generating from the
# default set would omit libgit2 and SQLite, which are the two entries with
# anything interesting to say.

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly root
readonly out="$root/THIRD-PARTY.md"

for tool in cargo jq; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        printf '%s is required to regenerate the notices\n' "$tool" >&2
        exit 2
    fi
done

# Into a temporary and checked, for the reason scripts/lint/test-gates.sh
# exists: a generator whose input silently failed writes a file saying this
# software ships nothing.
graph="$(mktemp)"
rendered="$(mktemp)"
trap 'rm -f "$graph" "$rendered"' EXIT

if ! cargo metadata --format-version 1 --all-features \
    --manifest-path "$root/router/Cargo.toml" >"$graph" 2>/dev/null; then
    printf 'could not read the dependency graph; nothing was written\n' >&2
    exit 2
fi

count="$(jq -r '[.packages[] | select(.name != "wattrouter")] | length' "$graph")"
if [ "$count" -lt 2 ]; then
    printf 'the graph reported %s packages, which cannot be right\n' "$count" >&2
    exit 2
fi

{
    cat <<'PREAMBLE'
# Third-party notices

Generated by `scripts/notices.sh` from the dependency graph. Do not edit below the line —
run the script.

The applications built from this repository statically link everything here. MIT and
Apache-2.0 both require the licence and copyright notice to travel with a binary
distribution, which makes this an obligation rather than a courtesy, and the moment it
matters is the first time somebody is handed an APK.

## The three a generated list gets wrong

**libgit2 is GPL-2.0 with a linking exception, and nothing in the metadata says so.**
`libgit2-sys` declares `MIT OR Apache-2.0`, which covers the Rust binding and not the C it
vendors and compiles. The exception is what makes linking it from a differently-licensed
program permissible, and it is the one entry in this file that needs a person.

**SQLite is public domain.** `libsqlite3-sys` declares MIT for its binding and bundles
SQLite's own amalgamation, which its authors dedicated to the public domain. Nothing is owed
and this line exists so nobody re-derives it.

**`option-ext` is MPL-2.0** — the only weak copyleft in the graph, reached through `dirs`
under `fastembed`. Linking is unrestricted; the obligation is source availability for those
files, satisfied by the crate being published. Named here rather than left to be found during
a licence audit.

## The Android side

Jetpack Compose, AndroidX and the Kotlin standard library are Apache-2.0 and arrive through
Gradle rather than cargo, so they are not in the list below. They are listed at the layer
rather than enumerated because their versions come from one bill of materials
(`androidx.compose:compose-bom`), and enumerating a resolved graph that a single line moves
would be the stale-copy problem again.

## The iOS side

Nothing. The application links this repository's own core and Apple's frameworks.

---
PREAMBLE

    printf '\n## Rust dependencies (%s packages, all features)\n\n' "$count"

    jq -r '
        [.packages[] | select(.name != "wattrouter") | .license // "not declared"]
        | group_by(.) | map({licence: .[0], n: length}) | sort_by(-.n) | .[]
        | "| \(.licence) | \(.n) |"
    ' "$graph" |
        {
            printf '| Licence | Packages |\n|---|---|\n'
            cat
        }

    printf '\n<details>\n<summary>Every package</summary>\n\n'
    printf '| Package | Version | Licence |\n|---|---|---|\n'
    jq -r '
        [.packages[] | select(.name != "wattrouter")]
        | sort_by(.name)
        | .[]
        | "| \(.name) | \(.version) | \(.license // "not declared") |"
    ' "$graph"
    printf '\n</details>\n'
} >"$rendered"

if [ "${1:-}" = "--check" ]; then
    if diff -q "$rendered" "$out" >/dev/null 2>&1; then
        printf 'notices: THIRD-PARTY.md is current\n'
        exit 0
    fi
    printf 'notices: THIRD-PARTY.md is out of date. Run scripts/notices.sh\n' >&2
    diff -u "$out" "$rendered" | head -40 >&2 || true
    exit 1
fi

mv "$rendered" "$out"
trap 'rm -f "$graph"' EXIT
printf 'notices: wrote %s (%s packages)\n' "$out" "$count"
